replicaCount: 1

image:
  repository: gohar262/book-catalog
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000

ingress:
  enabled: false
  className: nginx
  annotations: {}
  hosts:
    - host: book-catalog.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources: {}

env:
  DEBUG: "True"
