name: CI/CD Pipeline with kind

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: ${{ secrets.DOCKER_IMAGE_NAME }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests
        run: python manage.py test

      - name: Install Docker CLI (needed for kind)
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io

      - name: Install kind
        run: |
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.20.0/kind-linux-amd64
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind

      - name: Create kind cluster
        run: |
          kind create cluster --name book-catalog-cluster

      - name: Build Docker image for kind cluster
        run: |
          docker build -t $IMAGE_NAME:${{ github.sha }} .
          kind load docker-image $IMAGE_NAME:${{ github.sha }} --name book-catalog-cluster

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: "latest"

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: "v3.13.0"

      - name: Deploy with Helm to kind cluster
        run: |
          helm upgrade --install book-catalog ./helm \
            --set image.repository=$IMAGE_NAME \
            --set image.tag=${{ github.sha }}
